# dmesg -T | grep -i 'killed process'
name: Frontend runner
on:
  push:
    branches: ["main"]

jobs:
  react:
    defaults:
      run:
        working-directory: v2
    runs-on: self-hosted
    steps:
      - name: Update repository recook.ru
        uses: actions/checkout@v3
      - name: ReactAPP build up
        run: docker compose --progress plain up --build -d
